const APP_STATE = {assistant:{mode:'article',messages:[]},uniqueness:{internal:null,external:null}};
const ALLOWED_SUGGESTION_FIELDS = new Set(['article_type','primary_query','secondary_queries','search_intent','short_answer','region','article_template','author_id','medical_reviewer_id','medical_reviewed_at','content_updated_at','sources','related_articles','result_name','result_preview','result_code']);
function $(id){return document.getElementById(id)}
function field(id){const el=$(id)||document.querySelector(`[name="${id}"]`);return el?el.value:''}
function setField(id,value){const el=$(id)||document.querySelector(`[name="${id}"]`);if(el){el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}))}}
function stripDangerousHtml(s){const t=document.createElement('template');t.innerHTML=String(s||'');t.content.querySelectorAll('script,style,iframe,form,noscript').forEach(n=>n.remove());return t.content.textContent||''}
async function sha256(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function normalizeText(text){return stripDangerousHtml(text).replace(/Записаться на при[её]м|Получить консультацию|Читайте также/gi,' ').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9\s-]/gi,' ').replace(/\s+/g,' ').trim()}
async function collectUniquenessText(){const parts=[field('result_name'),field('result_preview'),field('result_short_answer'),field('result_detail_html')];const normalized=normalizeText(parts.join('\n'));return {text:normalized,content_hash:await sha256(normalized)}}
function markUniquenessOutdated(){for(const k of ['internal','external'])if(APP_STATE.uniqueness[k]?.status==='completed')APP_STATE.uniqueness[k].status='outdated';renderInternalUniqueness();renderExternalUniqueness()}
async function callN8n(action,data={}){const r=await fetch('proxy.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data})});const j=await r.json().catch(()=>({success:false,error:{message:'Некорректный JSON'}}));if(!r.ok||j.success===false)throw new Error(j.error?.message||j.message||`HTTP ${r.status}`);return j.data||j}
async function runInternalUniqueness(){const payload=await collectUniquenessText();APP_STATE.uniqueness.internal={status:'processing',content_hash:payload.content_hash};renderInternalUniqueness();try{const data=await callN8n('internal_uniqueness',{...payload,source:field('source'),element_id:field('element_id')});APP_STATE.uniqueness.internal=data}catch(e){APP_STATE.uniqueness.internal={status:'failed',error:e.message}}renderInternalUniqueness()}
async function startExternalUniqueness(){const payload=await collectUniquenessText();APP_STATE.uniqueness.external={status:'processing',content_hash:payload.content_hash};sessionStorage.setItem('temed_external_hash',payload.content_hash);renderExternalUniqueness();try{const data=await callN8n('start_external_uniqueness',{...payload,exceptdomain:'temed.ru, *.temed.ru',copying:'noadd'});sessionStorage.setItem('temed_external_uid',data.uid||'');setTimeout(()=>pollExternalUniqueness(1),10000)}catch(e){APP_STATE.uniqueness.external={status:'failed',error:e.message};renderExternalUniqueness()}}
async function pollExternalUniqueness(attempt){if(attempt>40){APP_STATE.uniqueness.external={status:'failed',error:'TEXT.RU timeout'};return renderExternalUniqueness()}try{const data=await callN8n('get_external_uniqueness',{uid:sessionStorage.getItem('temed_external_uid'),content_hash:sessionStorage.getItem('temed_external_hash')});APP_STATE.uniqueness.external=data;if(data.status==='processing')setTimeout(()=>pollExternalUniqueness(attempt+1),15000)}catch(e){APP_STATE.uniqueness.external={status:'failed',error:e.message}}renderExternalUniqueness()}
function renderMatches(root,matches=[]){matches.slice(0,10).forEach(m=>{const d=document.createElement('div');d.className='match';d.textContent=`${m.name||m.url||m.element_id}: ${m.matched_percent||0}% — ${(m.fragments||[]).map(f=>f.text).join(' … ')}`;root.appendChild(d)})}
function renderInternalUniqueness(){const c=$('internal_uniqueness_card');if(!c)return;const s=APP_STATE.uniqueness.internal||{status:'not_started'};c.querySelector('.status').textContent=s.status;const b=c.querySelector('.body');b.textContent=s.error||`${s.uniqueness_percent??''}${s.uniqueness_percent?'% уникальности':''}`;renderMatches(b,s.matches)}
function renderExternalUniqueness(){const c=$('external_uniqueness_card');if(!c)return;const s=APP_STATE.uniqueness.external||{status:'not_started'};c.querySelector('.status').textContent=s.status;const b=c.querySelector('.body');b.textContent=s.error||`${s.uniqueness_percent??s.text_unique??''}${(s.uniqueness_percent||s.text_unique)?'% уникальности':''}`;renderMatches(b,s.matches)}
function collectAssistantContext(){return {current_step:Number(field('current_step')||1),article_context:{result_name:field('result_name'),result_preview:field('result_preview'),result_short_answer:field('result_short_answer'),primary_query:field('primary_query'),search_intent:field('search_intent')},uniqueness:APP_STATE.uniqueness}}
async function sendAssistantMessage(){const input=$('assistant_input');const message=input.value.trim();if(!message)return;APP_STATE.assistant.mode=$('assistant_mode').value;APP_STATE.assistant.messages.push({role:'user',content:message});renderAssistantMessage({role:'user',content:message});input.value='';const data=await callN8n('assistant_chat',{mode:APP_STATE.assistant.mode,message,current_step:collectAssistantContext().current_step,article_context:collectAssistantContext().article_context,conversation:APP_STATE.assistant.messages.slice(-20)});const msg={role:'assistant',content:data.answer||'',sources:data.sources||[],suggestions:data.suggestions||[],warnings:data.warnings||[]};APP_STATE.assistant.messages.push(msg);sessionStorage.setItem('temed_assistant_'+(field('generation_id')||'draft'),JSON.stringify(APP_STATE.assistant.messages.slice(-20)));renderAssistantMessage(msg)}
function renderAssistantSources(box,sources=[]){sources.forEach(s=>{const d=document.createElement('div');d.className='assistant-source';d.textContent=[s.type,s.path,s.action,s.commit_sha,s.section].filter(Boolean).join(' · ');box.appendChild(d)})}
function renderAssistantSuggestions(box,suggestions=[]){suggestions.forEach(s=>{const d=document.createElement('div');d.className='assistant-suggestion';d.textContent=`${s.label||s.field_id}: ${s.reason||''}`;const btn=document.createElement('button');btn.textContent='Применить';btn.onclick=()=>applyAssistantSuggestion(s);d.appendChild(btn);box.appendChild(d)})}
function renderAssistantMessage(msg){const box=document.createElement('div');box.className='assistant-msg '+(msg.role||'assistant');box.textContent=msg.content||'';renderAssistantSources(box,msg.sources);renderAssistantSuggestions(box,msg.suggestions);$('assistant_messages')?.appendChild(box)}
function applyAssistantSuggestion(s){if(!ALLOWED_SUGGESTION_FIELDS.has(s.field_id))return alert('Поле запрещено для изменения');const cur=field(s.field_id);if(confirm(`Заменить значение поля ${s.field_id}?\n\nТекущее: ${cur}\n\nНовое: ${s.value}\n\nМедицинский смысл при необходимости требует повторной проверки.`))setField(s.field_id,s.value)}
async function downloadBitrixXml(){const data={};document.querySelectorAll('input,textarea,select').forEach(el=>{if(el.name||el.id)data[el.name||el.id]=el.value});const r=await fetch('export.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const blob=await r.blob();const filename=(r.headers.get('X-Export-Filename')||'bitrix-article.xml').replace(/[\\/]/g,'');if(!r.ok){$('save_result').textContent=await blob.text();return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href);$('save_result').textContent=`Имя файла: ${filename}\nСтатус: неактивна\nДата формирования: ${new Date().toLocaleString()}\nКоличество заполненных свойств: ${r.headers.get('X-Filled-Properties')||''}\nПредупреждения: ${decodeURIComponent(r.headers.get('X-Export-Warnings')||'')}`}
document.addEventListener('input',e=>{if(['result_name','result_preview','result_short_answer','result_detail_html'].includes(e.target.id||e.target.name))markUniquenessOutdated()});document.addEventListener('DOMContentLoaded',()=>{$('check_internal')?.addEventListener('click',runInternalUniqueness);$('check_external')?.addEventListener('click',startExternalUniqueness);$('check_all')?.addEventListener('click',()=>{runInternalUniqueness();startExternalUniqueness()});$('assistant_send')?.addEventListener('click',sendAssistantMessage);$('assistant_clear')?.addEventListener('click',()=>{$('assistant_messages').textContent='';APP_STATE.assistant.messages=[]});$('assistant_toggle')?.addEventListener('click',()=>$('assistant_panel').classList.toggle('open'));$('download_xml_btn')?.addEventListener('click',downloadBitrixXml)});
