<?php
declare(strict_types=1);session_start();
$allowed=['bootstrap','article_structures','load_existing_article','research_sources','generate_outline','approve_outline','generate_article','extract_med_questions','apply_med_answers','validate_article','revise_article','assistant_chat','start_external_uniqueness','get_external_uniqueness','internal_uniqueness','system_manifest'];
$timeouts=['assistant_chat'=>45,'start_external_uniqueness'=>20,'get_external_uniqueness'=>20,'internal_uniqueness'=>60,'system_manifest'=>10];
function fail($m,$c=400){http_response_code($c);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['success'=>false,'error'=>['message'=>$m]],JSON_UNESCAPED_UNICODE);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST')fail('Only POST is allowed',405);$body=json_decode(file_get_contents('php://input'),true);if(!is_array($body))fail('Invalid JSON');$action=(string)($body['action']??'');$data=$body['data']??[];if(!in_array($action,$allowed,true))fail('Action is not allowed',403);
if($action==='assistant_chat'){if(mb_strlen((string)($data['message']??''))>10000)fail('message too long');if(count((array)($data['conversation']??[]))>20)fail('conversation too long');}
if(isset($data['detail_html'])&&mb_strlen((string)$data['detail_html'])>300000)fail('detail_html too long');
if($action==='system_manifest'){echo json_encode(['success'=>true,'data'=>['api_version'=>'1.0','editor_version'=>'1.0','deployed_commit'=>trim(shell_exec('git rev-parse HEAD 2>/dev/null')?:''),'article_iblock_id'=>81,'legacy_article_iblock_id'=>68,'available_actions'=>$allowed,'article_properties'=>['847'=>'ARTICLE_TYPE','848'=>'PRIMARY_QUERY','849'=>'SECONDARY_QUERIES','850'=>'SEARCH_INTENT','851'=>'SHORT_ANSWER','852'=>'REGION','853'=>'AUTHOR','854'=>'MEDICAL_REVIEWER','855'=>'MEDICAL_REVIEWED_AT','856'=>'CONTENT_UPDATED_AT','857'=>'SOURCES','858'=>'RELATED_ARTICLES','864'=>'ARTICLE_TEMPLATE'],'structure_versions'=>[],'public_file_hashes'=>array_filter(['editor.html'=>is_file('editor.html')?hash_file('sha256','editor.html'):null,'editor.js'=>is_file('editor.js')?hash_file('sha256','editor.js'):null,'editor.css'=>is_file('editor.css')?hash_file('sha256','editor.css'):null,'proxy.php'=>is_file('proxy.php')?hash_file('sha256','proxy.php'):null])]],JSON_UNESCAPED_UNICODE);exit;}
$webhook=getenv('TEMED_N8N_WEBHOOK_URL');if(!$webhook)fail('N8N webhook is not configured',501);$ch=curl_init($webhook);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode(['action'=>$action,'data'=>$data],JSON_UNESCAPED_UNICODE),CURLOPT_TIMEOUT=>$timeouts[$action]??90]);$resp=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($resp===false)fail(curl_error($ch),502);http_response_code($code?:200);header('Content-Type: application/json; charset=UTF-8');echo $resp;
